schema_version: 1

context:
  version: "1.5.0"
  home: https://quantumai.google/cirq
  summary: >-
    Python package for writing, manipulating, and running quantum circuits
    on quantum computers.
  doc_url: https://quantumai.google/cirq/install
  python_min: '3.10'

recipe:
  name: cirq-meta
  version: ${{ version }}

source:
  url: https://github.com/quantumlib/Cirq/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ff1622dea7de12e58fc47458e30d576c9a5a4faba5fd85bc6849150d1da3fc7f

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: cirq-core
    build:
      noarch: python
      script: |
        cd cirq-core
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - attrs >=25.3.0
        - duet-python >=0.2.8
        - matplotlib-base >=3.0,<4
        - networkx >=3.4.0
        - numpy >=1.26
        - pandas
        - sortedcontainers >=2.0,<3
        - scipy >=1.0,<2
        - sympy
        - typing_extensions >=4.14.0
        - tqdm
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-core
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-core/LICENSE

  - package:
      name: cirq-aqt
    build:
      noarch: python
      script: |
        cd cirq-aqt
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
        - requests >=2.32.4,<3
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_aqt
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-aqt
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-aqt/LICENSE

  - package:
      name: cirq-web
    build:
      noarch: python
      script: |
        cd cirq-web
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_web
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-web
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-web/LICENSE

  - package:
      name: cirq-rigetti
    build:
      noarch: python
      script: |
        cd cirq-rigetti
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
        - pyquil >=4.11.0, <5.0.0
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_rigetti
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-rigetti
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-rigetti/LICENSE

  - package:
      name: cirq-pasqal
    build:
      noarch: python
      script: |
        cd cirq-pasqal
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
        - requests >=2.32.4,<3
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_pasqal
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-pasqal
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-pasqal/LICENSE

  - package:
      name: cirq-ionq
    build:
      noarch: python
      script: |
        cd cirq-ionq
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
        - requests >=2.32.4,<3
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_ionq
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-ionq
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-ionq/LICENSE

  - package:
      name: cirq-google
    build:
      noarch: python
      script: |
        cd cirq-google
        ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-core ==${{ version }}
        - google-api-core-grpc >=1.14.0
        - protobuf >=5.29.5
        - proto-plus >=1.26.0
        - typedunits
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq_google
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq/tree/master/cirq-google
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: cirq-google/LICENSE

  - package:
      name: cirq
    build:
      noarch: python
      script: ${PYTHON} -m pip install . -vv --no-deps
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools >=70
      run:
        - python >=${{ python_min }}
        - cirq-aqt ==${{ version }}
        - cirq-core ==${{ version }}
        - cirq-google ==${{ version }}
        - cirq-ionq ==${{ version }}
        - cirq-pasqal ==${{ version }}
        - cirq-rigetti ==${{ version }}
        - cirq-web ==${{ version }}
    tests:
      - python:
          python_version:
            - ${{ python_min }}.*
          imports:
            - cirq
    about:
      homepage: ${{ home }}
      summary: ${{ summary }}
      repository: https://github.com/quantumlib/Cirq
      documentation: ${{ doc_url }}
      license: Apache-2.0
      license_file: LICENSE

about:
  homepage: ${{ home }}
  summary: ${{ summary }}
  description: >-
    Cirq is a Python library for writing, manipulating, and optimizing quantum
    circuits and running them against quantum computers and simulators. It
    provides useful abstractions for dealing with today’s noisy
    intermediate-scale quantum (NISQ) computers, where the details of quantum
    hardware are vital to achieving state-of-the-art results.
  repository: https://github.com/quantumlib/Cirq
  documentation: ${{ doc_url }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - BastianZim
  feedstock-name: cirq
